---
title: "RWorksheet_Aposaga#4a"
author: "John Philipp Aposaga"
date: "2024-10-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1
#a
```{r}
shoeSize <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0)
Height <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0)
Gender <- c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M", "M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M")
SHG <- data.frame(shoeSize, Height, Gender)
names(SHG) <- c("Shoe Size", "Height", "Gender")
SHG

```



#b
```{r}
SHG_male <- subset(SHG, Gender == "M")
SHG_male

SHG_female <- subset(SHG, Gender == "F")
SHG_female
```
#c
```{r}
mean(shoeSize)
mean(Height)
```
#d
#There is no relationship between the two variables, since a person's shoe size is different from their height, although they are both attributes of a respondent.

#2
```{r}
months <- c("March", "April", "January", "November", "January", "September", "October", "September", "November", "August", "January", "November", "November", "February", "May", "August", "July", "December", "August", "August", "September", "November", "February", "April")
factor_months_vector <- factor(months)
factor_months_vector
```
#3
```{r}
summary(months)
summary(factor_months_vector)
```
#4
```{r}
factor_data <- c("East", "West", "North")
freq <- c(1,4,3)

new_order_data <- factor(factor_data, levels = c("East", "West", "North"))
new_order_data

fdata <- data.frame(Direction = factor_data, Frequency = freq)
fdata
```
#5
```{r}
importmarch <- read.table("import_march.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
importmarch
```
#6
```{r}
selnum <- as.numeric(readline(prompt = "Select a number from 1 to 50: "))

if (is.na(selnum) || selnum < 1 || selnum > 50) {
  print("The number selected is beyond the range of 1 to 50.")
} else if (selnum == 20) {
  print("TRUE")
} else {
  print(paste("The selected number is", selnum))
}
```
#7
```{r}

min_bills <- function(price){
  bills <- c(1000, 500, 200, 100, 50) 
  count <- 0  
  
  for(bill in bills) {
    if(price >= bill) {
      count <- count + price %/% bill 
      price <- price %% bill
    }
  }
  
  cat("Minimum number of bills needed to purchase a snack:", count, "\n")
}

min_bills(1550)
```
#8a
```{r}
Name <- c("Annie", "Thea", "Steve", "Hanna")
Grade1 <- c(85, 65, 75, 95)
Grade2 <- c(65, 75, 55, 75)
Grade3 <- c(85, 90, 80, 100)
Grade4 <- c(100, 90, 85, 90)

grades <- data.frame(Name, Grade1, Grade2, Grade3, Grade4)
grades
```
#8b
```{r}
ave_grades <- apply(grades[,2:5], 1, function(x) sum(x) / length(x) )
ave_grades

high_achievers <- grades$Name[ave_grades > 90]
high_achiever_averages <- ave_grades[ave_grades > 90]

for (i in 1:nrow(grades)) {
  if (ave_grades[i] > 90) {
    cat(grades$Name[i], "'s average grade this semester is ", ave_grades[i], ".\n", sep = "")
  }
}

```
#8c
```{r}
for (j in 2:5) {
  test_average <- sum(grades[, j]) / nrow(grades)
  if (test_average < 80) {
    cat("The ", names(grades)[j], " test was difficult.\n", sep = "")
  }
}
```
#8d
```{r}
for (i in 1:nrow(grades)) {
  
  highest_grade <- sort(as.numeric(grades[i, 2:5]), decreasing = TRUE)[1]
  if (highest_grade > 90) {
    cat(grades$Name[i], "'s highest grade this semester is ", highest_grade, ".\n", sep = "")
  }
}
```













